### ISSUE TITLE
cannot install it with pip3

### ISSUE THREAD

**Issue by Mebus** [rbit/pydtls#23]
Hello!

For some reason I cannot install this via pip3:

``Collecting Dtls
  Downloading https://files.pythonhosted.org/packages/06/bb/dcd7fd37b109b7b63d9fec5c5a25f5842e699e864a0c10ca8448c6bb1f04/Dtls-1.2.0.tar.gz (79kB)
    100% |████████████████████████████████| 81kB 1.2MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wclkc1_6/Dtls/setup.py", line 53, in <module>
        long_description = open("README.md").read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
``

Mebus

**Comment by vladimirbaranov-mobius** [comment]
It is developed for python 2. I am trying to use It under python3 too

**Comment by yotamss** [comment]
Look for python3-dtls
