### ISSUE TITLE
Library Updates for 2024

### ISSUE THREAD

**Issue by frobnitzem** [rbit/pydtls#29]
This project [pypi:Dtls](https://pypi.org/project/Dtls) seems to have been re-released and updated as [pypi:python3-dtls](https://pypi.org/project/python3-dtls/), which exists at [github:mcfreis/pydtls](https://github.com/mcfreis/pydtls).

Unfortunately, [github:mcfreis/pydtls](https://github.com/mcfreis/pydtls) is a fork, so can't handle its own issues.  It also does not appear to have all its tests modernized to python3.

Most urgently, loading [github:mcfreis/pydtls](https://github.com/mcfreis/pydtls)
shows that the openssl wrapper has been affected by bitrot between libssl.so.1.1 and libssl.so.3:

```
dtls% python3
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dtls
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/virtualenvs/dtls-test-KDGpXqcR-py3.10/lib/python3.10/site-packages/dtls/__init__.py", line 63, in <module>
    from .patch import do_patch
  File "/virtualenvs/dtls-test-KDGpXqcR-py3.10/lib/python3.10/site-packages/dtls/patch.py", line 44, in <module>
    from .sslconnection import SSLConnection, PROTOCOL_DTLS, PROTOCOL_DTLSv1, PROTOCOL_DTLSv1_2
  File "/virtualenvs/dtls-test-KDGpXqcR-py3.10/lib/python3.10/site-packages/dtls/sslconnection.py", line 61, in <module>
    from .x509 import _X509, decode_cert
  File "/virtualenvs/dtls-test-KDGpXqcR-py3.10/lib/python3.10/site-packages/dtls/x509.py", line 34, in <module>
    from .openssl import *
  File "/virtualenvs/dtls-test-KDGpXqcR-py3.10/lib/python3.10/site-packages/dtls/openssl.py", line 660, in <module>
    list(map(lambda x: _make_function(*x), (
  File "/virtualenvs/dtls-test-KDGpXqcR-py3.10/lib/python3.10/site-packages/dtls/openssl.py", line 660, in <lambda>
    list(map(lambda x: _make_function(*x), (
  File "/virtualenvs/dtls-test-KDGpXqcR-py3.10/lib/python3.10/site-packages/dtls/openssl.py", line 570, in _make_function
    func = _sigs[sig]((name, lib), tuple((i[2] if len(i) > 2 else 1,
AttributeError: /lib/x86_64-linux-gnu/libssl.so.3: undefined symbol: SSL_get_peer_certificate
>>> exit()
```

Fixing this could ideally be done by replacing dtls/x509 and dtls/openssl by community-supported wrappers from [py/cryptography](https://cryptography.io).

Anyone willing to support / take on this task?

**Comment by rbit** [comment]
You are right - since Python 2 is deprecated, I no longer maintain this project. However, I do sometimes accept contracts for work such as this. If you're interested in that, let me know.
